name: Notify Triagers

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  Notify-triagers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Check PR Changes for .md files
        id: md-pr-changes
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **.md

      - name: Check PR Changes for non-.md files
        id: non-md-pr-changes
        uses: tj-actions/changed-files@v42
        with:
          files: |
            !**.md

      - name: Read triagers.json
        if: steps.md-pr-changes.outputs.any_changed == 'true' || steps.non-md-pr-changes.outputs.any_changed == 'true'
        id: read-triagers-json
        run: |
          mdTriagers=$(jq -r '.mdTriagers[]' triagers.json | tr '\n' ' ')
          codeTriagers=$(jq -r '.codeTriagers[]' triagers.json | tr '\n' ' ')
          echo "md-triagers=$mdTriagers" >> $GITHUB_OUTPUT
          echo "code-triagers=$codeTriagers" >> $GITHUB_OUTPUT

      - name: Store comments to file
        if: steps.md-pr-changes.outputs.any_changed == 'true' || steps.non-md-pr-changes.outputs.any_changed == 'true'
        run: |
          if [ -f existing_comments.txt ]; then
            rm existing_comments.txt
          fi
          echo "[file-type: md]" >> existing_comments.txt
          echo "[file-type: non-md]" >> existing_comments.txt

      - name: Add Reviewers
        if: steps.md-pr-changes.outputs.any_changed == 'true' || steps.non-md-pr-changes.outputs.any_changed == 'true'
        run: |
          reviewers=(${{ steps.read-triagers-json.outputs.code-triagers }} ${{ steps.read-triagers-json.outputs.md-triagers }})
          reviewers=$(echo "${reviewers[@]}" | tr ' ' ',')
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{
              "reviewers": ['"${reviewers}"']
            }'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
